### ISSUE TITLE
New elementary OS runtime

### ISSUE THREAD

**Issue by Alecaddd** [flathub/com.github.akiraux.akira#5]
elementary OS finally released version 6, and with that, they released the stable SDK runtime v6 which includes stylesheet and icons.
Do you think that would work as a replacement for what we're currently doing? (importing styles and icons and installing them).
@bilelmoussaoui

**Comment by hfiguiere** [comment]
This would be an issue for https://github.com/flathub/io.elementary.BaseApp to upgrade

**Comment by albfan** [comment]
@Alecaddd probably we should move to elementary appcenter. Looks like elementary sdk will not be available on flathub. Am I right @bilelmoussaoui? I guess this will never be available from flathub:

```
runtime: io.elementary.Platform
runtime-version: '6'
sdk: io.elementary.Sdk
```

Does elementary accept beta apps? I'm not sure about their policies. @danrabbit might clarify that, but probably we should remove Akira from flathub.

**Comment by Alecaddd** [comment]
I'm preparing the release of Akira for AppCenter, and it's not a problem the fact that we're still in alpha.
I want to keep releasing Akira as a general flatpak app in FlatHub like we're doing now, by using the `io.elementary.BaseApp` and compiling stylesheet and icons on build.

I think these 2 release process can stay separate and work without issues.

**Comment by albfan** [comment]
Posted a question on flathub forum: https://discourse.flathub.org/t/distributing-runtimes-and-sdk/1640

Without distributing runtime and sdk from flathub, will be counterintuitive to add the elementary remote only for runtime and sdk. Adding that already will add Akira from elementary repository.

Maintain in flathub will be pointless.

I suspect nobody wants to maintain a bad clone from elementary sdk here, if there's an official one. Probably this repo should be archived and point to elementary sdk

**Comment by albfan** [comment]
FTR:

```
$ flatpak remote-add --if-not-exists --system elementary-appcenter https://flatpak.elementary.io/repo.flatpakrepo
$ flatpak install akira
Buscando coincidencias…
Found similar ref(s) for ‘akira’ in remote ‘elementary’ (system).
Use this remote? [Y/n]: Y
Found ref ‘app/com.github.akiraux.akira/x86_64/stable’ in remote ‘elementary’ (system).
Use this ref? [Y/n]: Y
Required runtime for com.github.akiraux.akira/x86_64/stable (runtime/io.elementary.Platform/x86_64/6) found in remote elementary
Do you want to install it? [Y/n]: Y
```

**Comment by Alecaddd** [comment]
Great stuff, I'll drop the other flatpak and update the readme.

**Comment by hfiguiere** [comment]
so basically you just abandon `aarch64` user since elementary only build for intel 64-bits.

**Comment by danirabbit** [comment]
@hfiguiere FWIW we're currently working on getting cross compilation going in AppCenter. We should have arm builds working soon

**Comment by hfiguiere** [comment]
`arm` or `aarch64`?

**Comment by Alecaddd** [comment]
Honestly, the next version of Akira will probably be released Q1 of 2022 due to the massive architectural rework we're going through.
When that day comes, I'm sure the elementary devs will have improved a lot of things as the core objective is "AppCenter for everyone", and of course if something is not completed yet, we will do a secondary release on flathub as a temporary fix.
No need to start screaming about abandoning users, no one wants to do that.

**Comment by hfiguiere** [comment]
The simple talk of moving the package to where there is no aarch64 support, while I have been working hard to increase the amount of apps for aarch64 on flathub, is discouraging.

**Comment by cassidyjames** [comment]
> `arm` or `aarch64`?

ARM (generically), and specifically `aarch64` as that's what our Raspberry Pi 4 and Pinebook Pro builds are. The elementary Platform is already being built for `aarch64`, and we're working to enable it for all AppCenter apps by default.
